### ISSUE TITLE
Add Variables that can be substituted into other values

### ISSUE THREAD

**Issue by andrewdmay** [LeadingEDJE/stackmanager#36]
Currently only `Environment` and `Region` are substituted into Parameters, Tags, StackName using Jinja2 templates.

In some cases this can be limiting - for example if rather than using the "Environment" value you have a code for that environment that you want to use instead in Parameters or as part of a parameter (e.g. a Parameter Store key).

Adding a Variables section containing values that can be substituted would address this issue. The variables would be inherited and merged, but there would be no templating.

This seems safer and less complex than allowing something like recursive evaluation of parameters into other parameters.

Example usage:

```yaml
---
Environment: all
Parameters:
  EnvCode: "{{ EnvCode }}"
  SSMKey: /VPC/{{ EnvCode }}/Subnet1
---
Environment: test
Variables:
  EnvCode: t
```
